# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marcin/Sites/Studia/SOP2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marcin/Sites/Studia/SOP2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marcin/Sites/Studia/SOP2/CMakeFiles /Users/marcin/Sites/Studia/SOP2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marcin/Sites/Studia/SOP2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SOP2

# Build rule for target.
SOP2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SOP2
.PHONY : SOP2

# fast build rule for target.
SOP2/fast:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/build
.PHONY : SOP2/fast

src/builtin.o: src/builtin.c.o
.PHONY : src/builtin.o

# target to build an object file
src/builtin.c.o:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/builtin.c.o
.PHONY : src/builtin.c.o

src/builtin.i: src/builtin.c.i
.PHONY : src/builtin.i

# target to preprocess a source file
src/builtin.c.i:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/builtin.c.i
.PHONY : src/builtin.c.i

src/builtin.s: src/builtin.c.s
.PHONY : src/builtin.s

# target to generate assembly for a file
src/builtin.c.s:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/builtin.c.s
.PHONY : src/builtin.c.s

src/helpers.o: src/helpers.c.o
.PHONY : src/helpers.o

# target to build an object file
src/helpers.c.o:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/helpers.c.o
.PHONY : src/helpers.c.o

src/helpers.i: src/helpers.c.i
.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.c.i:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/helpers.c.i
.PHONY : src/helpers.c.i

src/helpers.s: src/helpers.c.s
.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.c.s:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/helpers.c.s
.PHONY : src/helpers.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/main.c.s
.PHONY : src/main.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) -f CMakeFiles/SOP2.dir/build.make CMakeFiles/SOP2.dir/src/parser.c.s
.PHONY : src/parser.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SOP2"
	@echo "... src/builtin.o"
	@echo "... src/builtin.i"
	@echo "... src/builtin.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

